using System;
using Klydis.Core.Chat;

namespace Klydis.Core.Inference;

/// <summary>
/// Classified outcome of an inference generation step.
/// </summary>
public enum GenerationOutcome
{
    /// <summary>Visible text was produced by the model.</summary>
    VisibleMessage,

    /// <summary>A valid tool call was produced by the model.</summary>
    ToolAction,

    /// <summary>Model generated tokens, but no visible text or valid tool action was emitted (e.g. thinking-only stream).</summary>
    ThinkingOnly,

    /// <summary>Model generated zero tokens (transport returned empty).</summary>
    TransportEmpty,

    /// <summary>Generation was never started because no token budget remained in the context window.</summary>
    ContextFull,

    /// <summary>Generation was stopped by cancellation.</summary>
    Cancelled,

    /// <summary>Tool syntax appeared in the output but could not be parsed safely.</summary>
    MalformedToolCall,

    /// <summary>A degenerate generation loop was detected mid-stream.</summary>
    LoopDetected
}

/// <summary>
/// Immutable structured result representing the outcome and metrics of a single generation step.
/// </summary>
public sealed record GenerationResult
{
    /// <summary>Unique identifier for this generation step.</summary>
    public required string GenerationId { get; init; }

    /// <summary>Identifier of the model that executed the generation, if known.</summary>
    public string? ModelId { get; init; }

    /// <summary>Number of prompt tokens evaluated during prefill.</summary>
    public int PromptTokenCount { get; init; }

    /// <summary>Total number of tokens generated by the model.</summary>
    public int GeneratedTokenCount { get; init; }

    /// <summary>Number of thinking / reasoning tokens generated.</summary>
    public int ThinkingTokenCount { get; init; }

    /// <summary>Number of visible / content tokens generated.</summary>
    public int VisibleTokenCount { get; init; }

    /// <summary>Classified outcome of the generation step.</summary>
    public GenerationOutcome Outcome { get; init; }

    /// <summary>Reason generation stopped (e.g. stop token, max tokens, cancellation, loop detector).</summary>
    public string? StopReason { get; init; }

    /// <summary>Information about any degenerate generation loop detected during the step.</summary>
    public GenerationLoopInfo? LoopInfo { get; init; }

    /// <summary>True if the generation was aborted or stopped by cancellation.</summary>
    public bool WasCancelled { get; init; }

    /// <summary>True if the generation could not start because the context window was full.</summary>
    public bool WasContextFull { get; init; }
}
