using System;
using System.Collections.Generic;
using System.Text.Json;
using System.Threading.Tasks;

namespace Klydis.Core.Capabilities;

/// <summary>
/// Domain category of a machine capability for taxonomy and graph routing.
/// </summary>
public enum CapabilityDomain
{
    Hardware,
    OperatingSystem,
    Filesystem,
    Process,
    Desktop,
    Browser,
    Software,
    Development,
    Network,
    Remote,
    LocalAI,
    Shell
}

/// <summary>
/// Safety policy tier for a capability.
/// </summary>
public enum PolicyDefault
{
    /// <summary>Safe non-destructive inspection or operation that can run automatically.</summary>
    Auto,

    /// <summary>Mutating or impactful operation requiring user confirmation in supervised mode.</summary>
    Confirm,

    /// <summary>High-risk or sensitive operation blocked by default.</summary>
    Deny
}

/// <summary>
/// Operating authority mode configured for Klydis.
/// </summary>
public enum AuthorityMode
{
    /// <summary>Unrestricted local machine execution for verified local deployments.</summary>
    LocalFullControl,

    /// <summary>Standard supervised execution requiring confirmation for mutations.</summary>
    StandardSupervised,

    /// <summary>Strict read-only execution; all mutating capabilities are denied.</summary>
    StrictReadOnly
}

/// <summary>
/// Parameter definition for a machine capability.
/// </summary>
public sealed record CapabilityParameter(
    string Name,
    string Type,
    string Description,
    bool Required,
    IReadOnlyList<string>? EnumValues = null,
    object? DefaultValue = null
);

/// <summary>
/// Detailed description of a capability exposed to the planning engine and model.
/// </summary>
public sealed record CapabilityDescription(
    string Id,
    CapabilityDomain Domain,
    string Description,
    IReadOnlyList<CapabilityParameter> Parameters,
    PolicyDefault Policy = PolicyDefault.Auto,
    IReadOnlyList<string>? RequiredPreconditions = null,
    IReadOnlyList<string>? ExpectedPostconditions = null
);

/// <summary>
/// Request to execute a specific capability.
/// </summary>
public sealed record CapabilityRequest(
    string CapabilityId,
    IReadOnlyDictionary<string, object?> Parameters,
    string? TaskId = null,
    string? RunId = null,
    string? Reason = null,
    DateTime? Timestamp = null
)
{
    public DateTime? Timestamp { get; init; } = Timestamp ?? DateTime.UtcNow;

    public T? GetParam<T>(string name, T? defaultValue = default)
    {
        if (Parameters.TryGetValue(name, out var val) && val is not null)
        {
            if (val is T typedVal) return typedVal;
            if (val is JsonElement je)
            {
                try
                {
                    return JsonSerializer.Deserialize<T>(je.GetRawText());
                }
                catch
                {
                    return defaultValue;
                }
            }

            try
            {
                return (T)Convert.ChangeType(val, typeof(T));
            }
            catch
            {
                return defaultValue;
            }
        }
        return defaultValue;
    }
}

/// <summary>
/// Structured evidence produced by a capability invocation.
/// </summary>
public sealed record CapabilityEvidence(
    string Source,
    string RawOutput,
    DateTime CollectedAtUtc,
    IReadOnlyDictionary<string, object?>? StructuredMetrics = null
);

/// <summary>
/// Classification of a side effect generated by capability execution.
/// </summary>
public enum SideEffectKind
{
    StateModified,
    ProcessSpawned,
    ProcessTerminated,
    FileMutated,
    FileCreated,
    FileDeleted,
    WindowModified,
    NetworkTraffic,
    ServiceChanged,
    EnvironmentChanged
}

/// <summary>
/// Record of a side effect produced by capability execution.
/// </summary>
public sealed record SideEffect(
    SideEffectKind Kind,
    string Target,
    string Description,
    bool IsReversible = false,
    Func<Task>? RevertAction = null
);

/// <summary>
/// The result of executing a machine capability.
/// </summary>
public sealed record CapabilityResult(
    string CapabilityId,
    bool Success,
    object? Data,
    string? Error,
    TimeSpan Duration,
    IReadOnlyList<SideEffect>? SideEffects = null,
    CapabilityEvidence? Evidence = null,
    int? ExitCode = null
)
{
    public static CapabilityResult Succeeded(
        string capabilityId,
        object? data,
        TimeSpan duration,
        CapabilityEvidence? evidence = null,
        IReadOnlyList<SideEffect>? sideEffects = null,
        int? exitCode = 0) =>
        new(capabilityId, true, data, null, duration, sideEffects ?? Array.Empty<SideEffect>(), evidence, exitCode);

    public static CapabilityResult Failed(
        string capabilityId,
        string error,
        TimeSpan duration,
        CapabilityEvidence? evidence = null,
        int? exitCode = -1) =>
        new(capabilityId, false, null, error, duration, Array.Empty<SideEffect>(), evidence, exitCode);
}

/// <summary>
/// Evaluation of whether preconditions are satisfied before capability execution.
/// </summary>
public sealed record PreconditionCheckResult(
    bool IsSatisfied,
    string? FailureReason = null,
    IReadOnlyList<string>? MissingRequirements = null
)
{
    public static PreconditionCheckResult Satisfied() => new(true);
    public static PreconditionCheckResult Failed(string reason, IReadOnlyList<string>? missingRequirements = null) =>
        new(false, reason, missingRequirements);
}

/// <summary>
/// Epistemic assertion to be recorded in or removed from the Fact Ledger.
/// </summary>
public sealed record FactAssertion(
    string Domain,
    string EntityKey,
    string PropertyName,
    object Value,
    TimeSpan Ttl,
    string SourceCapability,
    double Confidence = 1.0
);

/// <summary>
/// Result of postcondition verification after execution.
/// </summary>
public sealed record VerificationResult(
    bool IsVerified,
    string Explanation,
    IReadOnlyList<FactAssertion>? EstablishedFacts = null,
    IReadOnlyList<FactAssertion>? InvalidatedFacts = null
)
{
    public static VerificationResult Verified(string explanation, IReadOnlyList<FactAssertion>? establishedFacts = null) =>
        new(true, explanation, establishedFacts ?? Array.Empty<FactAssertion>(), Array.Empty<FactAssertion>());

    public static VerificationResult Failed(string explanation, IReadOnlyList<FactAssertion>? invalidatedFacts = null) =>
        new(false, explanation, Array.Empty<FactAssertion>(), invalidatedFacts ?? Array.Empty<FactAssertion>());
}
