using System;
using System.Collections.Generic;

namespace Klydis.Core.Tasks;

/// <summary>
/// Initializes baseline execution plan schema representations for actionable requests.
/// The Plan/TODO system starts with zero tasks: the runtime defines the schema and execution state machine,
/// while the model generates the substantive plan content from scratch based on the objective,
/// available capabilities, and world state.
/// </summary>
public static class InitialPlanGenerator
{
    /// <summary>
    /// Returns the initial task checklist for a new objective.
    /// In accordance with the runtime schema architecture, new goals start with zero tasks.
    /// Substantive tasks are generated by the model/planner rather than hardcoded workflow templates.
    /// </summary>
    public static IReadOnlyList<string> Generate(string userMessage)
    {
        // A new goal starts with zero tasks.
        return Array.Empty<string>();
    }

    /// <summary>
    /// Creates a fresh <see cref="ExecutionPlan"/> schema initialized for the objective with zero tasks.
    /// </summary>
    public static ExecutionPlan CreateInitialPlan(string objective)
    {
        return new ExecutionPlan(
            objective: objective ?? string.Empty,
            tasks: Array.Empty<PlanTask>(),
            completion: new CompletionCriteria(Array.Empty<string>()));
    }
}
